### ISSUE TITLE
Projet "discrimination raciale"

### ISSUE THREAD

**Issue by tanninaham** [YoannDupont/PPE#55]
https://github.com/gemmafelton/PPE-group

**Comment by YoannDupont** [comment]
Bonjour,

Je n'arrive pas à accéder à votre git. Est-ce la bonne adresse et est-il public ?

**Comment by gemmafelton** [comment]
Bonjour, 

Nous avons rectifié l'erreur et notre git est maintenant accessible.

**Comment by YoannDupont** [comment]
C'est ok !
